config/routes.rb
DataRb::Application.routes.draw do
  resources :data_sets do
    member do
      get :chart
      get :multichart
    end
  end

  match '/algorithms/:id/linear_regression'   => 'algorithms#linear_regression',   :as => :linear_regression

  match '/algorithms/:id/logistic_regression' => 'algorithms#logistic_regression', :as => :logistic_regression

  root :to => 'welcome#index'
end

app/models/data_set.rb
require 'csv'
#
# NOTE (farleyknight@gmail.com): This class will probably become
# a mere interface overtime..
#
# Anything that has a set of columns & a collection of instances
# is technically a 'dataset', so obviously any ActiveRecord
# class fits the bill..
#
class DataSet < ActiveRecord::Base
  PROBLEM_TYPES = %w(categorical regression clustering)

  def columns
    CSV.parse(column_names).first
  end

  def column_range
    (0..column_range_min)
  end

  def column_range_min
    [columns.size-1, 6].min
  end

  def size
    @size ||= data.size
  end

  alias :m :size

  def categories
    unless self[:categories].blank?
      CSV.parse(self[:categories]).first.map {|c| c.strip }
    else
      []
    end
  end

  def raw_data
    CSV.parse(self[:data])
  end

  def data
    raw_data.map do |row|
      row.map do |cell|
        if cell =~ /[0-9]*\.[0-9]*/
          cell.to_f
        elsif cell =~ /[0-9]*/
          cell.to_i
        else
          cell
        end
      end
    end
  end

  def matrix
    NMatrix[*data]
  end

  def regression?
    problem_type == "regression"
  end

  def categorical?
    problem_type == "categorical"
  end

  ######################
  # Data Visualization #
  ######################

  def chart
    formatted_data = data.map do |row|
      row.map do |cell|
        cell.to_f
      end
    end

    {
      :data   => formatted_data,
      :x_axis => columns.first,
      :y_axis => columns.second
    }
  end

  def data_by_category(category)
    data.select do |row|
      row.last.strip == category.strip
    end
  end

  # NOTE (farleyknight@gmail.com): This method will provide a 2D matrix
  # of values, comparing row = r & column = c, filtering on the
  # category
  def compare_by_category(r, c, category)
    data_by_category(category).map do |row|
      [row[c.to_i].to_f, row[r.to_i].to_f]
    end
  end

  def compare_without_category(r, c)
    data.map do |row|
      [row[c.to_i].to_f, row[r.to_i].to_f]
    end
  end

  # NOTE (farleyknight@gmail.com): Does the same as above, but against
  # all categories. Used for spitting out some JSON to the UI
  def compare(r, c)
    if categorical?
      categories.map do |cat|
        {
          :category => cat,
          :data     => compare_by_category(r, c, cat)
        }
      end
    else
      [{:data => compare_without_category(r, c)}]
    end
  end

  def multichart
    column_range.map do |r|
      column_range.map do |c|
        unless r == c
          compare(r, c)
        else
          columns[r]
        end
      end
    end
  end

  ##########
  # Models #
  ##########

  def linear_regression
    model = Algorithms::LinearRegression.new
    model.fit(x_padded, y)
    model
  end

  def x
    @x ||= matrix[0..-2, 0..-1]
  end

  # Pad the X observation matrix with a column of ones on the left
  # for the 0th coefficient:
  #
  # c0 + c1*x1 + c2*x2 + ...
  #
  def x_padded
    ones = NMatrix.ones(1,m).to_a.flatten
    NMatrix[*([ones] + x.transpose.to_a)].transpose
  end

  def y
    matrix[-1, 0..-1]
  end
end

app/controllers/algorithms_controller.rb
class AlgorithmsController < ApplicationController
  def linear_regression
    @data_set = DataSet.find(params[:id])

    respond_to do |format|
      format.json do
        render :json => {
          :model => @data_set.linear_regression.model
        }
      end

      format.html do
        render :action => "linear_regression"
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/data_sets_controller.rb
class DataSetsController < ApplicationController
  def index
    @data_sets = DataSet.all
  end

  def new
    @data_set = DataSet.new
  end

  def show
    @data_set = DataSet.find(params[:id])

    respond_to do |format|
      format.html do
        render :action => "show"
      end
    end
  end

  def compare
    @data_set = DataSet.find(params[:id])

    respond_to do |format|
      format.json do
        render :json => @data_set.compare(params[:r], params[:c])
      end
    end
  end

  def chart
    @data_set = DataSet.find(params[:id])

    if @data_set.regression?
      render :json => {
        :chart => @data_set.chart,
        :model => @data_set.linear_regression.model
      }
    end
  end

  def multichart
    @data_set = DataSet.find(params[:id])

    if @data_set.regression?
      render :json => {
        :chart => @data_set.multichart,
        :model => @data_set.linear_regression.multimodel
      }
    elsif @data_set.categorical?
      render :json => @data_set.multichart
    end
  end

  def create
    @data_set = DataSet.create(params[:data_set])
    redirect_to :action => "show", :id => @data_set
  end

  def edit
    @data_set = DataSet.find(params[:id])
  end

  def update
    @data_set = DataSet.find(params[:id])
    @data_set.update_attributes(params[:data_set])
    redirect_to :action => "show", :id => @data_set
  end

  def destroy
    @data_set = DataSet.find(params[:id])
    @data_set.destroy
    redirect_to :action => "index"
  end
end

app/controllers/welcome_controller.rb
require 'csv'

class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/algorithms_helper.rb
module AlgorithmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/data_sets_helper.rb
module DataSetsHelper
  def javascript_array_for(data_set, r, c, category)
    data_set.compare(r, c, category)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def iris_dataset(r, c, opts = {})
    CSV.read("vendor/data/iris.txt").select do |row|
      row.last == opts[:category]
    end.map do |row|
      [row[r].to_f, row[c].to_f]
    end
  end
end

app/views/algorithms/linear_regression.html.erb
<h3 class="header">Linear Regression</h3>

<div id="linear_regression" data_set_id="<%= @data_set.id %>">
  <% if @data_set.columns.size == 2 %>
    <div id="chart"></div>
  <% elsif @data_set.columns.size > 2 %>
    <div id="multichart">
      <% @data_set.column_range.each do |r| %>
        <div>
          <% @data_set.column_range.each do |c| %>
            <div id="chart_<%= r %>_<%= c %>" class="data_box">
              <% if r == c %>
                <div class="inside">
                  <%= @data_set.columns[r] %>
                </div>
              <% end %>
            </div>
          <% end %>
          <div style="clear: both;">&nbsp;</div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/algorithms/logistic_regression.html.erb
<h3 class="header">Logistic Regression</h3>

<div id="logistic_regression" data_set_id="<%= @data_set.id %>">
  <% if @data_set.columns.size == 2 %>
    <div id="chart"></div>
  <% elsif @data_set.columns.size > 2 %>
    <div id="multichart">
      <% @data_set.column_range.each do |r| %>
        <div>
          <% @data_set.column_range.each do |c| %>
            <div id="chart_<%= r %>_<%= c %>" class="data_box">
              <% if r == c %>
                <div class="inside">
                  <%= @data_set.columns[r] %>
                </div>
              <% end %>
            </div>
          <% end %>
          <div style="clear: both;">&nbsp;</div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/data_sets/_chart.html.erb
<h3 class="header">Chart</h3>

<div id="chart"></div>

app/views/data_sets/_data.html.erb
<h3 class="header">Data</h3>

<table cellpadding="0" cellspacing="0" border="0" class="display" id="data_table" data_set_id="<%= data_set.id %>">
  <thead>
    <tr>
      <% data_set.columns.each do |c| %>
        <th><%= c %></th>
      <% end %>

      <% if data_set.categorical? %>
        <th>Category</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% data_set.data.each do |row| %>
      <tr>
        <% row.each do |cell| %>
          <td><%= cell %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/data_sets/_form.html.erb
<script>
  $(function() {
    $("#data_set_problem_type").change(function() {
      if ($(this).val() == "categorical") {
        $("#data_set_categories").show();
      } else {
        $("#data_set_categories").hide();
      }
    });
  });
</script>

<div>
  <label><b>Name</b></label>
  <%= f.text_field :name, :style => "width: 750px;" %>
</div>

<div>
  <label><b>Problem Type</b></label>
  <%= f.select :problem_type, DataSet::PROBLEM_TYPES.map {|i| [i.humanize, i] } %>
</div>

<div>
  <label><b>Column Names</b></label>
  <%= f.text_area :column_names, :style => "width: 750px; height: 20px;"  %>
</div>

<div id="data_set_categories" style="<%= 'display: none' unless @data_set.categorical? %>">
  <label><b>Categories</b></label>
  <%= f.text_area :categories,   :style => "width: 750px; height: 20px;"  %>
</div>

<div>
  <label><b>Data</b></label>
  <%= f.text_area :data, :style => "width: 750px; height: 200px; clear: both;" %>
</div>

<% if false %>
  <div>
    or
  </div>

  <div>
    <b>Upload (CSV):</b>
    <%= f.file_field :csv_file %>
  </div>
<% end %>

app/views/data_sets/_multichart.html.erb
<h3 class="header">Multichart</h3>

<div id="multichart">
  <% data_set.column_range.each do |r| %>
    <div>
      <% data_set.column_range.each do |c| %>
        <div id="chart_<%= r %>_<%= c %>" class="data_box">
          <% if r == c %>
            <div class="inside">
              <%= data_set.columns[r] %>
            </div>
          <% end %>
        </div>
      <% end %>
      <div style="clear: both;">&nbsp;</div>
    </div>
  <% end %>
</div>

app/views/data_sets/edit.html.erb
<h2>Edit DataSet</h2>

<div style="margin-top: 25px;">
  <%= form_for @data_set do |f| %>
    <%= render :partial => "data_sets/form", :locals => {:f => f} %>
    <button type="submit" class="btn">Update</button>
  <% end %>
</div>

app/views/data_sets/index.html.erb
<div style="margin-bottom: 20px; clear: both;">
  <h2 style="float: left;">DataSets</h2>

  <div style="float: right;">
    <%= link_to "New DataSet", new_data_set_path, :class => "btn" %>
  </div>
</div>

<div>&nbsp;</div>

<table style="width: 100%; margin-top: 20px; clear: both;">
  <tr>
    <th>Name</th>
    <th>Problem Type</th>
    <th># of Columns</th>
    <th># of Examples</th>
    <th></th>
  </tr>
  <% @data_sets.each do |data_set| %>
    <tr>
      <td><%= link_to data_set.name, data_set_path(data_set) %></td>
      <td style="text-align: center;"><%= data_set.problem_type %></td>
      <td style="text-align: center;"><%= data_set.columns.size %></td>
      <td style="text-align: center;"><%= data_set.size %></td>
      <td style="text-align: center;">
        <%= link_to "Edit",   edit_data_set_path(data_set) %> -
        <%= link_to "Delete", data_set_path(data_set), :method => :delete, :confirm => "Are you sure?" %>
      </td>
    </tr>
  <% end %>
</table>

app/views/data_sets/new.html.erb
<h2>New DataSet</h2>

<div style="margin-top: 25px;">
  <%= form_for @data_set do |f| %>
    <%= render :partial => "data_sets/form", :locals => {:f => f} %>
    <button type="submit" class="btn">Create</button>
  <% end %>
</div>

app/views/data_sets/show.html.erb
<h2><%= @data_set.name %></h2>

<% if @data_set.columns.size > 2 %>
  <%= render :partial => "data_sets/multichart", :locals => {:data_set => @data_set} %>
<% elsif @data_set.columns.size == 2 %>
  <%= render :partial => "data_sets/chart", :locals => {:data_set => @data_set} %>
<% end %>

<h3 class="header">Algorithms</h3>

<div id="algorithms">
  <% if @data_set.regression? %>
    <%= link_to "Linear Regression", linear_regression_path(@data_set) %>
  <% elsif @data_set.categorical? %>
    <%= link_to "Logistic Regression", logistic_regression_path(@data_set) %>
  <% end %>
</div>

<%= render :partial => "data_sets/data", :locals => {:data_set => @data_set}  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "data.rb" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">data.rb</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Data Sets", data_sets_path  %></li>
              <li><%= link_to "Data Sources", "#"  %></li>
              <li><%= link_to "Algorithms", "#"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
          <div class="span12">
            <%= yield %>
          </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer style="margin-top: 20px;">
        <p style="float: left;">&copy; Farley Knight 2012</p>

        <p style="float: right;">
          Powered by <%= link_to "ml.rb", "https://github.com/farleyknight/ml.rb" %>
        </p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>

app/views/layouts/application.html.old.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataRb</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div style="border-bottom: 1px solid black;">
      <%= link_to "DataSets", data_sets_path %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
Go to <%= link_to "Data Sets", data_sets_path %>